# Generated by Django 4.1.10 on 2023-08-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhone', models.IntegerField()),
                ('userAddress', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=15)),
            ],
        ),
    ]
